steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/google/perf_data_converter.git']
  id: perf_to_profile_1
  waitFor:
    - '-'

- name: busybox
  entrypoint: 'sed'
  args: ['-i', '-e', 's/\/\/src:__subpackage__/\/\/visibility:public/g',
    'perf_data_converter/src/BUILD']
  id: perf_to_profile_2
  waitFor:
    - 'perf_to_profile_1'

- name: gcr.io/cloud-builders/bazel
  args: ['build', '@perf_data_converter//src:perf_to_profile']
  id: perf_to_profile_3
  waitFor:
    - 'perf_to_profile_2'

artifacts:
  objects:
    location: 'gs://ymotongpoo-distribution'
    paths:
      - perf_data_converter/out/execroot/__main__/bazel-out/k8-fastbuild/bin/src/perf_to_profile

options:
  machineType: 'N1_HIGHCPU_8'